package com.reinhardjs.dsc_training.Training1.Fragments;

import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.reinhardjs.dsc_training.R;
import com.reinhardjs.dsc_training.Training1.RecyclerView.DummyData;
import com.reinhardjs.dsc_training.Training1.RecyclerView.RVAdapter;

import java.util.ArrayList;

public class FragmentRV extends Fragment {
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState){
        View view = inflater.inflate(R.layout.fragment_recyclerview, container, false);

        RecyclerView recyclerView = view.findViewById(R.id.recyclerView);

        LinearLayoutManager linearLayoutManager = new LinearLayoutManager(getContext());
        recyclerView.setLayoutManager(linearLayoutManager);

        ArrayList<DummyData> dataList = new ArrayList<>();
        dataList.add(new DummyData(R.drawable.image, "11111. consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\n\n 11111. consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna"));
        dataList.add(new DummyData(R.drawable.image, "22222. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\n\n11111. consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna"));
        dataList.add(new DummyData(R.drawable.image, "33333. adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\n\n11111. consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna"));
        dataList.add(new DummyData(R.drawable.image, "44444. dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna\n\n\n11111. consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna"));
        dataList.add(new DummyData(R.drawable.image, "55555. amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna\n\n\n11111. consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna"));
        dataList.add(new DummyData(R.drawable.image, "66666. ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna\n\n\n11111. consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna"));
        dataList.add(new DummyData(R.drawable.image, "77777. sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna\n\n\n11111. consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna"));
        dataList.add(new DummyData(R.drawable.image, "88888. adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna\n\n\n11111. consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna"));
        dataList.add(new DummyData(R.drawable.image, "99999. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna"));
        dataList.add(new DummyData(R.drawable.image, "10101. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla malesuada vel dolor fermentum laoreet. Fusce eget euismod quam, ultrices ultricies magna"));

        RVAdapter rvAdapter = new RVAdapter(getContext(), dataList, getActivity().getSupportFragmentManager());
        recyclerView.setAdapter(rvAdapter);

        return view;
    }
}
